# **_Load NumPy module_**

In [5]:
#Import NumPy library
import numpy as np

### The basic

In [52]:
#Create an array
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [48]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [49]:
# Get Dimension
a.ndim

1

In [50]:
# Get Shape
b.shape

(2, 3)

In [53]:
# Get Type
a.dtype

dtype('int16')

In [54]:
# Get Size
a.itemsize

2

In [55]:
# Get total size
a.nbytes

6

In [56]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [57]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [58]:
# Get a specific element [r, c]
a[1, 5]

13

In [59]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [61]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [62]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


**_3d_example_**

In [63]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [64]:
# Get specific element (work outside in)
b[0,1,1]

4

In [65]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [66]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Initialize different types of arrays

In [68]:
#All 0s matrix
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [69]:
#All 1s matrix
np.ones((3, 3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [70]:
#Full matrix with any other number
np.full((2, 3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [71]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4., 4.],
       [4., 4.]])

In [85]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.69734793, 0.33308731],
       [0.04312947, 0.89473339],
       [0.35277906, 0.04902741],
       [0.76408188, 0.5958972 ]])

In [90]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4,  4,  5],
       [ 6,  3,  3],
       [-3,  5,  5]])

In [91]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Create an array (problem 1)

In [9]:
#Create an array with full 1
a = np.ones((5, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
#Alter the inner border
a[1:4, 1:4] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
#Alter the center
a[2, 2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### _Be careful when copying arrays_

In [20]:
#Make sure to use the copy() function
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


### Mathematics

In [28]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [26]:
a + 2
print(a)

[3 4 5 6 7]


In [31]:
a - 2
print(a)

[1 2 3 4 5]


In [33]:
a *= 2
print(a)

[ 2  4  6  8 10]


In [34]:
b = np.array([1, 3, 5, 7, 9])
a + b

array([ 3,  7, 11, 15, 19])

In [38]:
a ** 2

array([  4,  16,  36,  64, 100], dtype=int32)

In [39]:
b ** 2

array([ 1,  9, 25, 49, 81], dtype=int32)

In [40]:
#Take the sin
np.sin(a)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111])

In [41]:
#Take the cosin
np.cos(a)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003, -0.83907153])

### _Linear algebra_

In [44]:
#Multiplication of matrices
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
#Find the determinants
c = np.identity(3)
np.linalg.det(c)

1.0

In [98]:
#Eigenvalues and eigenvectors of a matrix
a = np.full((3, 3), 3)
np.linalg.eig(a)

(array([ 9.00000000e+00,  9.86076132e-32, -6.22940318e-16]),
 array([[ 5.77350269e-01,  2.27155574e-16,  8.09500438e-01],
        [ 5.77350269e-01, -7.07106781e-01, -4.97117858e-01],
        [ 5.77350269e-01,  7.07106781e-01, -3.12382580e-01]]))

In [99]:
#Inverse of a matrix
a = np.array([[2, 1], [2, 3]])
np.linalg.inv(a)

array([[ 0.75, -0.25],
       [-0.5 ,  0.5 ]])

In [101]:
# Singular Vector Decomposition
a = np.array([[2, 3], [5, 7]])
np.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)

(array([[-0.38643579, -0.92231631],
        [-0.92231631,  0.38643579]]),
 array([9.32676279, 0.10721834]),
 array([[-0.57731211, -0.81652356],
        [ 0.81652356, -0.57731211]]))

In [103]:
#Matrix Norm
a = np.array([[1, 2, 3], [6, 7, 4], [5, 8, 9]])
np.linalg.norm(a, ord=None, axis=None, keepdims=False)

16.881943016134134

### _Statistics_

In [104]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
#Minimum value
np.min(stats)

1

In [106]:
#Maximum value
np.max(stats)

6

In [110]:
#Sum of the matrix
np.sum(stats)

21

### Reorganizing array

In [114]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [117]:
#Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [120]:
#Horizontal stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## MISCELLANOUS THINGS

### _Load data from file_

In [124]:
filedata = np.genfromtxt('D:\ANACONDA3\DATA.txt', delimiter = ',')
filedata.astype('int32')
print(filedata)

[[ 1.  4.  4.  4.  3.  2. 21.  4. 12. 21.  1.]
 [ 3.  4.  4.  5.  6.  8. 11. 13.  2.  4. 59.]]


### _Boolean Masking and Advanced Indexing_

In [128]:
filedata % 2 != 0

array([[ True, False, False, False,  True, False,  True, False, False,
         True,  True],
       [ True, False, False,  True, False, False,  True,  True, False,
        False,  True]])

In [129]:
filedata[filedata % 3 == 1]

array([ 1.,  4.,  4.,  4.,  4.,  1.,  4.,  4., 13.,  4.])

In [132]:
#You can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [133]:
np.any(filedata > 20, axis = 0)

array([False, False, False, False, False, False,  True, False, False,
        True,  True])

In [135]:
((filedata > 20) & (filedata < 50))

array([[False, False, False, False, False, False,  True, False, False,
         True, False],
       [False, False, False, False, False, False, False, False, False,
        False, False]])

## Problem 2

In [138]:
a = np.array([[1, 2, 3, 4, 5, 6], 
              [7, 8, 9, 10, 11, 12], 
              [13, 14, 15, 16, 17, 18], 
              [19, 20, 21, 22, 23, 24], 
              [25, 26, 27, 28, 29, 30]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [140]:
#Index problem 1
print(a[2 : 4, 0 : 2])

[[13 14]
 [19 20]]


In [141]:
#Index problem 2
print(a[[0, 1, 2, 3], [2, 3, 4, 5]])

[ 3 10 17 24]


In [144]:
print(a[[0, 3, 4], 4:])

[[ 5  6]
 [23 24]
 [29 30]]
